export const STATUS = {
  DO_NOT_CALL: 'DO NOT CALL',
  VERIFIED: 'VERIFIED',
  LEFT_VM: 'LEFT VM',
  WRONG_NUMBER: 'WRONG NUMBER',
  PENDING_VERIFICATION: 'PENDING VERIFICATION',
  RETURNED_TO_MINER: 'RETURNED TO MINER',
  NOT_IN_SERVICE: 'NOT IN SERVICE',
  DECEASED: 'DECEASED',
  NO_ANSWER: 'NO ANSWER',
  RING_OUT: 'RING OUT',
};

export const TAGS = {
  INTERESTED: 'INTERESTED',
  NOT_INTERESTED: 'NOT INTERESTED',
  CALL_BACK: 'CALL BACK',
  SOLD: 'SOLD',
  RESOLD: 'RESOLD',
  HOT_LEAD: 'HOT LEAD',
  UNVERIFIED: 'UNVERIFIED',
};
